// Mocks generated by Mockito 5.0.16 from annotations
// in travel_app/test/infrastructure/repositories/places_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_app/infrastructure/data/place_remote_data_source.dart'
    as _i3;
import 'package:travel_app/infrastructure/models/place_model.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

/// A class which mocks [PlaceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaceRemoteDataSource extends _i1.Mock
    implements _i3.PlaceRemoteDataSource {
  MockPlaceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i4.Future<List<_i5.PlaceModel>> getAllPlaces() => (super.noSuchMethod(
          Invocation.method(#getAllPlaces, []),
          returnValue: Future<List<_i5.PlaceModel>>.value(<_i5.PlaceModel>[]))
      as _i4.Future<List<_i5.PlaceModel>>);
  @override
  String toString() => super.toString();
}
